#pragma once

#include "UrhoBot.h"

#include "Urho3D/Core/CoreEvents.h"
#include "Urho3D/Scene/SceneEvents.h"
#include "Urho3D/Engine/Engine.h"
#include "Urho3D/UI/Font.h"
#include "Urho3D/Input/Input.h"
#include "Urho3D/Core/ProcessUtils.h"
#include "Urho3D/UI/Text.h"
#include "Urho3D/UI/UI.h"
#include "Urho3D/Resource/ResourceCache.h"
#include "Urho3D/UI/Sprite.h"
#include "Urho3D/DebugNew.h"
#include "Urho3D/Scene/Scene.h"
#include "Urho3D/Graphics/Graphics.h"
#include "Urho3D/IO/FileSystem.h"
#include "Urho3D/Engine/Console.h"
#include "Urho3D/Engine/DebugHud.h"
#include "Urho3D/IO/Log.h"

#include "Urho3D/Scene/Scene.h"
#include "Urho3D/Graphics/Octree.h"
#include "Urho3D/Graphics/StaticModel.h"
#include "Urho3D/Graphics/AnimatedModel.h"
#include "Urho3D/Graphics/AnimationState.h"
#include "Urho3D/Graphics/Light.h"
#include "Urho3D/Graphics/Model.h"
#include "Urho3D/Graphics/Material.h"
#include "Urho3D/Graphics/Camera.h"
#include "Urho3D/Graphics/Renderer.h"
#include "Urho3D/Graphics/Viewport.h"
#include "Urho3D/IO/FileSystem.h"
#include "Urho3D/Math/Plane.h"
#include "Urho3D/Graphics/Texture2D.h"

#include "Urho3D/Physics/PhysicsWorld.h"
#include "Urho3D/Physics/CollisionShape.h"
#include "Urho3D/Physics/PhysicsEvents.h"
#include "Urho3D/Core/Variant.h"

#include "Urho3D/Input/Controls.h"
#include "Urho3D/Scene/LogicComponent.h"
#include "Urho3D/IO/MemoryBuffer.h"

#include "Urho3D/Scene/ValueAnimation.h"
#include "Urho3D/Scene/ValueAnimationInfo.h"
#include "Urho3D/Graphics/DecalSet.h"
#include "Urho3D/IO/PackageFile.h"

#include "Urho3D/Navigation/NavigationMesh.h"
#include "Urho3D/Navigation/Navigable.h"
#include "Urho3D/Graphics/DebugRenderer.h"
